"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Skip R"
email = "tinyslices@gmail.com"

[ui]
default-command = ["log"]
diff-editor = ":builtin"
diff-instructions = false
diff-formatter = ":git"
graph.style = "curved"
log-word-wrap = true
pager = ["delta", "--hunk-header-style", "plain"]
paginate = "auto"

[git]
private-commits = "private"

[revsets]
# prioritize nearby commits
short-prefixes = "descendants(ancestors(@, 20), 3)"

[templates]
git_push_bookmark = '"skip/jj-" ++ change_id.short()'
draft_commit_description = '''
concat(
  description,
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.stat(72)),
  ),
)
'''

[template-aliases]
"format_short_id(id)" = "id.shortest()"
"format_timestamp(timestamp)" = "timestamp.ago()"
"format_short_signature(signature)" = "signature.name()"

[revset-aliases]
"private" = 'description(regex:"^(priv|private|PRIV|PRIVATE|p!):")'
"wip" = 'description(regex:"^\\[(wip|WIP|todo|TODO)\\]|(wip|WIP|todo|TODO):?") & mine() & mutable()'
