# MacBookAir10,1

{ darwin, home-manager, fenix, nixpkgs, ... }:

darwin.lib.darwinSystem {
  system = "aarch64-darwin";
  modules = [
    home-manager.darwinModule
    (import ../modules/nix.nix) { inherit nixpkgs; }
    (import ../modules/fenix.nix) { inherit fenix; }

    users.users.slice = {
      name = "slice";
      description = "Skip Rousseau";
    };

    home-manager.users.slice = (import ../home/home.nix) {};
    services.nix-daemon.enable = true;

    # generate system-wide run commands for shells to setup the nix environment.
    # typically though, run commands generated by home-manager are used instead.
    programs.zsh.enable = false; # disabled for now.
                                 # see: https://github.com/lnl7/nix-darwin/issues/373
    programs.fish.enable = true;

    system.stateVersion = 4;
  ];
  inputs = { pkgs = nixpkgs; };
}
