# MacBookAir10,1

{ darwin, home-manager, fenix, nixpkgs, ... }:

let filthyPkgs = import nixpkgs { config.allowUnfree = true; };
in darwin.lib.darwinSystem {
  system = "aarch64-darwin";
  modules = [
    ({ ... }: {
      users.users.slice = {
        name = "slice";
        description = "Skip Rousseau";
      };

      # home-manager.users.slice = (import ../home/home.nix) { };
      services.nix-daemon.enable = true;

      environment.systemPackages =
        [ home-manager.packages.aarch64-darwin.home-manager ];

      # generate system-wide run commands for shells to setup the nix environment.
      # typically though, run commands generated by home-manager are used instead.
      programs.fish.enable = true;
      # zsh integration is disabled for now.
      # see: https://github.com/lnl7/nix-darwin/issues/373
      programs.zsh.enable = false;

      system.stateVersion = 4;
    })

    # we need the raw flake input here
    (import ../modules/nix.nix { inherit nixpkgs; })
    (import ../modules/fenix.nix { inherit fenix; })
  ];
  inputs = { pkgs = filthyPkgs; };
}
